nelmio_cors:
    defaults:
        allow_credentials: false
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600

    paths:
        '^/':
            allow_origin:
                - 'https://morocan-crypto-web-dashboard-3bbm-5tr6t8uo8.vercel.app'
                - 'http://localhost:3000'
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
            allow_credentials: true
