nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['https://morocancryptobackend-production.up.railway.app']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['https://morocancryptobackend-production.up.railway.app']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
