nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['https://morocan-crypto-web-dashboard-3bbm-8adwa70d6.vercel.app']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['https://morocan-crypto-web-dashboard-3bbm-8adwa70d6.vercel.app']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
